POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "john-doe",
  "password": "password"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNDg5MDA5OCwiaWF0IjoxNzM0ODAzNjk4LCJqdGkiOiI0NzA1MTI5YWExOWI0OWU0ODYxYTZjMWMyNDVhYmMxOSIsInVzZXJfaWQiOjJ9.-3Dp755seB650FDFvuPX4T6sAoZ4VwAfJP2nNPRBBMI"
}

###

GET http://localhost:8000/api/products/ HTTP/1.1

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODU4MjE4LCJpYXQiOjE3MzQ4NTQ2MTgsImp0aSI6IjkxYzZmYjYyMzkwMTRiNmY4MDkzZGUwMTY5ZGVkY2U0IiwidXNlcl9pZCI6MX0.0KPz2pyEMGO8dTeApBiOapSAd-V_6rALwYFd6Y8vUfY

{
  "name": "Product 2",
  "description": "An amazing product!",
  "price": 199.0,
  "stock": 5
}

###

GET http://localhost:8000/api/products/9 HTTP/1.1

###

PUT http://localhost:8000/api/products/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODIxMzYzLCJpYXQiOjE3MzQ4MTc3NjMsImp0aSI6ImNhZjVkZTMxY2VjZTQyZWY4ZjVhYjFjNWQ4YjQxYjBjIiwidXNlcl9pZCI6MX0.li5Db2UyC0mdtpWe3fFwcoUMPm-BnHeQPtcCzRFTlA0

{
  "name": "TV",
  "description": "An amazing product!",
  "price": "200.00",
  "stock": 15
}

###

PATCH http://localhost:8000/api/products/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODIxMzYzLCJpYXQiOjE3MzQ4MTc3NjMsImp0aSI6ImNhZjVkZTMxY2VjZTQyZWY4ZjVhYjFjNWQ4YjQxYjBjIiwidXNlcl9pZCI6MX0.li5Db2UyC0mdtpWe3fFwcoUMPm-BnHeQPtcCzRFTlA0

{
  "name": "TV NEW"
}

###

DELETE http://localhost:8000/api/products/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODIxMzYzLCJpYXQiOjE3MzQ4MTc3NjMsImp0aSI6ImNhZjVkZTMxY2VjZTQyZWY4ZjVhYjFjNWQ4YjQxYjBjIiwidXNlcl9pZCI6MX0.li5Db2UyC0mdtpWe3fFwcoUMPm-BnHeQPtcCzRFTlA0

###

GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODAzNjI3LCJpYXQiOjE3MzQ4MDI3MjcsImp0aSI6ImViZjZjNzIwMDZlMTQ4OWU4M2UzMWRiMDhkMzA1NjkzIiwidXNlcl9pZCI6Mn0.eLHqa-kTuQmUoW1ksbTvt-ltU3KNbo3DnLrSkinAP7o

###

GET http://localhost:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1OTc2MzU0LCJpYXQiOjE3MzU5NzI3NTQsImp0aSI6IjEzOTc1NTMxYmUyMDQ5YTQ5NjI0OWMxYTc2YmMyMDI3IiwidXNlcl9pZCI6MX0.oVasUZr7oPwN733qnYXwlxUcfC_0X-K08Tbw-gz_WxA

###

POST http://localhost:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1OTc2MzU0LCJpYXQiOjE3MzU5NzI3NTQsImp0aSI6IjEzOTc1NTMxYmUyMDQ5YTQ5NjI0OWMxYTc2YmMyMDI3IiwidXNlcl9pZCI6MX0.oVasUZr7oPwN733qnYXwlxUcfC_0X-K08Tbw-gz_WxA

{
    "status": "Confirmed",
    # "user": 1,
    "items": [
      {
        "product": 1,
        "quantity": 1
      },
      {
        "product": 2,
        "quantity": 1
      }
    ]
  }