services:

  # Backend service
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  # Database service
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  # Proxy service
  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
      - "80:8000"
      # - "8000:8000"
    volumes:
      - static-data:/vol/static
    depends_on:
      - app

# Volumes
volumes:
  postgres-data:
  static-data:
