# Generated by Django 5.1.4 on 2025-02-24 08:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('amenity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the appliance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of the appliance.')),
                ('brand', models.CharField(blank=True, help_text='The manufacturer or brand of the appliance.', max_length=255)),
                ('model', models.CharField(blank=True, help_text='The model designation or number.', max_length=255)),
                ('serial_number', models.CharField(blank=True, help_text='The serial number of the appliance.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
                'db_table': 'appliances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Language name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest'), ('partner', 'Partner'), ('homeowner', 'Homeowner'), ('designer', 'Designer'), ('architect', 'Architect'), ('developer', 'Developer'), ('contractor', 'Contractor'), ('engineer', 'Engineer'), ('supplier', 'Supplier'), ('vendor', 'Vendor'), ('agent', 'Agent'), ('broker', 'Broker'), ('inspector', 'Inspector'), ('appraiser', 'Appraiser'), ('investor', 'Investor'), ('lender', 'Lender'), ('tenant', 'Tenant'), ('advisor', 'Advisor')], default='homeowner', help_text='The name of the role.', max_length=20, unique=True, verbose_name='Role Name')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='User email address, used as the username for login.', max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=150, null=True, verbose_name='Last Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', help_text='Current user status.', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the admin site.', verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Superuser')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('guest', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('openhouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('virtual', 'Virtual'), ('in-person', 'In-Person')], default='in-person', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('deleted', 'Deleted')], default='inactive', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, null=True)),
                ('virtual_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'openhouses',
            },
        ),
        migrations.CreateModel(
            name='OpenHouseAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_openhouses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('openhouse', models.ForeignKey(db_column='openhouse_id', on_delete=django.db.models.deletion.CASCADE, to='core.openhouse')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'openhouse_agents',
            },
        ),
        migrations.AddField(
            model_name='openhouse',
            name='agents',
            field=models.ManyToManyField(related_name='openhouses', through='core.OpenHouseAgent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('organization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the organization or firm.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the organization.', null=True)),
                ('website', models.URLField(blank=True, help_text="The organization's website URL.", max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the organization.', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address for the organization.', max_length=254, null=True)),
                ('address', models.ForeignKey(blank=True, help_text='Physical address of the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='core.OrderItem', to='core.product'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('profile_id', models.BigAutoField(help_text='Unique identifier for the profile.', primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('mobile_phone', models.CharField(blank=True, help_text='Mobile phone number.', max_length=50, null=True, verbose_name='Mobile Phone')),
                ('profile_picture', models.CharField(blank=True, help_text='URL or path to the profile picture.', max_length=255, null=True, verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth.", null=True, verbose_name='Date Of Birth')),
                ('bio', models.TextField(blank=True, help_text='Short biography of the user.', null=True, verbose_name='Biography')),
                ('cv', models.CharField(blank=True, help_text="Link or path to the user's CV.", max_length=255, null=True, verbose_name='Curriculum Vitae')),
                ('job_title', models.CharField(blank=True, help_text="The user's current job title.", max_length=100, null=True, verbose_name='Job Title')),
                ('address', models.OneToOneField(blank=True, db_column='address_id', help_text='The address associated with this profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.address', verbose_name='Address')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization this user profile is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['role_assignment__user__email'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], default='fluent', help_text='Language proficiency level', max_length=20, verbose_name='Proficiency')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to='core.language')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_languages', to='core.profile')),
            ],
            options={
                'db_table': 'profile_languages',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(help_text='Languages known by the user.', related_name='profiles', through='core.ProfileLanguage', to='core.language', verbose_name='Languages'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('property_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the property listing.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the property.')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse')], default='house', help_text='Type of property (e.g., House, Apartment, etc.).', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price of the property as determined by the seller or agent.', max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the property is currently available on the market.')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates if the property is published or still in draft.')),
                ('lot_area', models.PositiveIntegerField(blank=True, help_text='Total area of the lot in square meters', null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total livable area within the structure in square meters.', max_digits=8, null=True)),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height of the ceiling in meters.', max_digits=4, null=True)),
                ('num_floors', models.PositiveIntegerField(blank=True, help_text='Total number of floors (stories) in the property', null=True)),
                ('num_rooms', models.PositiveIntegerField(blank=True, help_text='Total number of rooms in the property.', null=True)),
                ('num_bathrooms', models.PositiveIntegerField(blank=True, help_text='Total number of bathrooms in the property.', null=True)),
                ('num_parking', models.PositiveIntegerField(blank=True, help_text='Total number of parking spaces available with the property.', null=True)),
                ('open_parking', models.BooleanField(default=False, help_text='Indicates if open (uncovered) parking spaces are available.')),
                ('covered_parking', models.BooleanField(default=False, help_text='Indicates if covered (garage) parking spaces are available.')),
                ('year_built', models.DateField(blank=True, help_text='The date when the property was built.', null=True)),
                ('tax_assessed_value', models.DecimalField(decimal_places=2, help_text='Property value as per the latest tax assessment.', max_digits=12)),
                ('tax_annual_amount', models.DecimalField(decimal_places=2, help_text='Annual property tax amount.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks regarding the property.', null=True)),
                ('address', models.OneToOneField(blank=True, db_column='address_id', help_text='Address of the property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.address')),
                ('appliances', models.ManyToManyField(blank=True, help_text='List of appliances included with the property.', related_name='properties', to='core.appliance')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(db_column='user_id', help_text='Owner of the property.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='openhouse',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property'),
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('tx_hash', models.CharField(max_length=66)),
                ('event_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'verbose_name': 'Timestamp',
                'verbose_name_plural': 'Timestamps',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, related_name='amenity_properties', to='core.amenity')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='core.property')),
            ],
            options={
                'db_table': 'property_amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.', verbose_name='Updated At')),
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'db_table': 'property_photos',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to=core.models.recipe_image_file_path)),
                ('ingredients', models.ManyToManyField(to='core.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.recipetag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reviewer', models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Name for the tag.', max_length=100, verbose_name='Tag Name')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User who created this tag.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'db_table': 'tagged_items',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('profile', models.OneToOneField(blank=True, db_column='profile_id', help_text='Profile automatically created for this role assignment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='core.profile', verbose_name='Profile')),
                ('role', models.ForeignKey(db_column='role_id', help_text='The role assigned to the user.', on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User to whom this role is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'users_roles',
                'ordering': ['user', 'role'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role_assignment',
            field=models.OneToOneField(help_text='The user role assignment linked to this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_link', to='core.userrole', verbose_name='Role Assignment'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(help_text='Roles assigned to the user.', related_name='users', through='core.UserRole', to='core.role', verbose_name='Assigned Roles'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available', 'is_published'], name='properties_is_avai_6c895a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties_price_aa33af_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['created_at'], name='core_blockc_created_e38dff_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['updated_at'], name='core_blockc_updated_7351ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenity'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name'], name='tags_tag_nam_91d860_idx'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['tag'], name='tagged_item_tag_id_a534cb_idx'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['content_type', 'object_id'], name='tagged_item_content_cb60fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='users_roles_user_id_84b8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['profile'], name='users_roles_profile_82088a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['organization'], name='profiles_organiz_0a4ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['job_title'], name='profiles_job_tit_53f829_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth'], name='profiles_date_of_b6769c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'status'], name='users_email_f7aa6a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='users_first_n_0c5a67_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='users_last_na_5e9a3c_idx'),
        ),
    ]
