# Generated by Django 5.1.4 on 2025-02-15 22:18

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the appliance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of the appliance.')),
                ('brand', models.CharField(blank=True, help_text='The manufacturer or brand of the appliance.', max_length=255)),
                ('model', models.CharField(blank=True, help_text='The model designation or number.', max_length=255)),
                ('serial_number', models.CharField(blank=True, help_text='The serial number of the appliance.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
                'db_table': 'appliances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Language name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='User email address, used as the username for login.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=150, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', help_text='Current user status.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('openhouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('virtual', 'Virtual'), ('in-person', 'In-Person')], default='in-person', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('deleted', 'Deleted')], default='inactive', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, null=True)),
                ('virtual_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'openhouses',
            },
        ),
        migrations.CreateModel(
            name='OpenHouseAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_openhouses', to=settings.AUTH_USER_MODEL)),
                ('openhouse', models.ForeignKey(db_column='openhouse_id', on_delete=django.db.models.deletion.CASCADE, to='core.openhouse')),
            ],
            options={
                'db_table': 'openhouse_agents',
            },
        ),
        migrations.AddField(
            model_name='openhouse',
            name='agents',
            field=models.ManyToManyField(related_name='openhouses_agent', through='core.OpenHouseAgent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the organization or firm.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the organization.', null=True)),
                ('website', models.URLField(blank=True, help_text="The organization's website URL.", max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the organization.', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address for the organization.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, help_text='Physical address of the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.address')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='core.OrderItem', to='core.product'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('cv', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.address')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization this user (profile) is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], default='fluent', help_text='Language proficiency level', max_length=20)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to='core.language')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_languages', to='core.profile')),
            ],
            options={
                'db_table': 'profile_languages',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(related_name='profiles', through='core.ProfileLanguage', to='core.language'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the property listing.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the property.')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse')], default='house', help_text='Type of property (e.g., House, Apartment, etc.).', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price of the property as determined by the seller or agent.', max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the property is currently available on the market.')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates if the property is published or still in draft.')),
                ('lot_area', models.PositiveIntegerField(blank=True, help_text='Total area of the lot in square meters', null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total livable area within the structure in square meters.', max_digits=8, null=True)),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height of the ceiling in meters.', max_digits=4, null=True)),
                ('num_floors', models.PositiveIntegerField(blank=True, help_text='Total number of floors (stories) in the property', null=True)),
                ('num_rooms', models.PositiveIntegerField(blank=True, help_text='Total number of rooms in the property.', null=True)),
                ('num_bathrooms', models.PositiveIntegerField(blank=True, help_text='Total number of bathrooms in the property.', null=True)),
                ('num_parking', models.PositiveIntegerField(blank=True, help_text='Total number of parking spaces available with the property.', null=True)),
                ('open_parking', models.BooleanField(default=False, help_text='Indicates if open (uncovered) parking spaces are available.')),
                ('covered_parking', models.BooleanField(default=False, help_text='Indicates if covered (garage) parking spaces are available.')),
                ('year_built', models.DateField(blank=True, help_text='The date when the property was built.', null=True)),
                ('tax_assessed_value', models.DecimalField(decimal_places=2, help_text='Property value as per the latest tax assessment.', max_digits=12)),
                ('tax_annual_amount', models.DecimalField(decimal_places=2, help_text='Annual property tax amount.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks regarding the property.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, db_column='address_id', help_text='Address of the property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.address')),
                ('appliances', models.ManyToManyField(blank=True, help_text='List of appliances included with the property.', related_name='properties', to='core.appliance')),
                ('owner', models.ForeignKey(db_column='user_id', help_text='Owner of the property.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='openhouse',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('event_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to=core.models.recipe_image_file_path)),
                ('ingredients', models.ManyToManyField(to='core.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.recipetag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for the tag.', max_length=100)),
                ('created_by', models.ForeignKey(help_text='User who created this tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest'), ('partner', 'Partner'), ('homeowner', 'Homeowner'), ('designer', 'Designer'), ('architect', 'Architect'), ('developer', 'Developer'), ('contractor', 'Contractor'), ('engineer', 'Engineer'), ('supplier', 'Supplier'), ('vendor', 'Vendor'), ('agent', 'Agent'), ('broker', 'Broker'), ('inspector', 'Inspector'), ('appraiser', 'Appraiser'), ('investor', 'Investor'), ('lender', 'Lender'), ('tenant', 'Tenant'), ('advisor', 'Advisor')], default='homeowner', max_length=20)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('reviewer', models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'property_photos',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='language',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag')),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering.', related_name='%(class)s_tags', to='core.tag'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(blank=True, db_column='profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='core.profile')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_link', to='core.userrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='core.UserRole', to='core.role', verbose_name='Assigned roles to the user.'),
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, related_name='amenity_properties', to='core.amenity')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='core.property')),
            ],
            options={
                'db_table': 'property_amenities',
                'constraints': [models.UniqueConstraint(fields=('property', 'amenity'), name='unique_property_amenity')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available', 'is_published'], name='properties_is_avai_6c895a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties_price_aa33af_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'status'], name='users_email_f7aa6a_idx'),
        ),
    ]
