# Generated by Django 5.1.4 on 2024-12-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cvv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
    ]
