# Generated by Django 5.1.4 on 2024-12-23 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_cvv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cvv",
            new_name="cv",
        ),
    ]
